use_sim: False
obs_res: [84, 84]
workspace: [3.5, 4.2, 0.65, 0.75]

robot:
  arm_ip: 192.168.1.2
  hand_ip: 192.168.1.11
  local_ip: 192.168.1.9
  local_port: 50003
  sim.start_config: [0.5, -1.692 , 2.635, -0.943, 1.57 ,-0.262]
  sim.use_gui: True

sim_scene:
  cup_size: 0.10
  cameras:
    cam1:
      cameraEyePosition: [-1.0, -0.6, 0.2]
      cameraTargetPosition: [0, 0.2, 0]
      cameraUpVector: [0, 0, 1]
      fov: 70

real_scene:
  detector_cam_id: 1
  out_position: Joints(1.28, -1.692 , 2.635, -0.943, 1.57 ,-0.262)
  neutral_position: None
  cameras:
    cam1:
      id: 0
      type: k4a
